INSERT IGNORE INTO roles(name)
VALUES ('ROLE_USER');
INSERT IGNORE INTO roles(name)
VALUES ('ROLE_ADMIN');

INSERT IGNORE INTO privileges(name)
VALUES ('READ_PRIVILEGE');
INSERT IGNORE INTO privileges(name)
VALUES ('WRITE_PRIVILEGE');
INSERT IGNORE INTO privileges(name)
VALUES ('CHANGE_PASSWORD_PRIVILEGE');