apiVersion: apps/v1
kind: StatefulSet                    # Type of the kubernetes resource
metadata:
  name: app-quotes-mysql           # Name of the deployment
  labels: # Labels applied to this deployment
    app: app-quotes-mysql
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels: # This deployment applies to the Pods matching the specified labels
      app: app-quotes-mysql
      tier: mysql
  strategy:
    type: Recreate
  template: # Template for the Pods in this deployment
    metadata:
      labels: # Labels to be applied to the Pods in this deployment
        app: app-quotes-mysql
        tier: mysql
    spec: # The spec for the containers that will be run inside the Pods in this deployment
      containers:
      - image: tobi312/rpi-mariadb:10.3-alpine
        name: mysql
        envFrom: # Environment variables passed to the container
          - secretRef: # Read environment variables from kubernetes secrets
              name: app-quotes-mysql-secret
        ports:
          - containerPort: 3306        # The port that the container exposes
            name: mysql
        volumeMounts:
          - name: mysql-persistent-storage  # This name should match the name specified in `volumes.name`
            mountPath: /var/lib/mysql1
      volumes: # A PersistentVolume is mounted as a volume to the Pod
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
---
apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource
metadata:
  name: app-quotes-mysql         # Name of the resource
  labels: # Labels that will be applied to the resource
    app: app-quotes-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector: # Selects any Pod with labels `app=polling-app,tier=mysql`
    app: app-quotes-mysql
    tier: mysql