apiVersion: v1
kind: Secret
metadata:
  name: app-quotes-mysql-secret
type: Opaquels
stringData:
  DATASOURCE_URL: jdbc:mariadb://app-quotes-mysql:3306/app_quotes?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false

  MYSQL_ROOT_PASSWORD: password
  MYSQL_DATABASE: app_quotes
  MYSQL_USER: mybatis
  MYSQL_PASSWORD: mybatis$